package frc.robot.constants.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories, and removes the need
 * for JSON parsing to load a trajectory's essential data. DO NOT MODIFY THIS FILE YOURSELF! It is
 * automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue) {
  public static final ChoreoTraj ReturnLeft =
      new ChoreoTraj(
          "ReturnLeft",
          OptionalInt.empty(),
          3.70123,
          new Pose2d(7.8, 5, Rotation2d.fromRadians(-1.7)),
          new Pose2d(2.3, 5.9, Rotation2d.fromRadians(-0.68)));
  public static final ChoreoTraj ReturnRight =
      new ChoreoTraj(
          "ReturnRight",
          OptionalInt.empty(),
          3.70103,
          new Pose2d(7.8, 3.069, Rotation2d.fromRadians(1.7)),
          new Pose2d(2.3, 2.169, Rotation2d.fromRadians(0.68)));
  public static final ChoreoTraj RushLeft =
      new ChoreoTraj(
          "RushLeft",
          OptionalInt.empty(),
          3.16618,
          new Pose2d(3, 7.5, Rotation2d.fromRadians(0)),
          new Pose2d(7.8, 5, Rotation2d.fromRadians(-1.7)));
  public static final ChoreoTraj RushRight =
      new ChoreoTraj(
          "RushRight",
          OptionalInt.empty(),
          3.16613,
          new Pose2d(3, 0.569, Rotation2d.fromRadians(0)),
          new Pose2d(7.8, 3.069, Rotation2d.fromRadians(1.7)));

  /**
   * A map between trajectory names and their corresponding data. This allows for trajectory data to
   * be looked up with strings during runtime.
   */
  public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES =
      Map.ofEntries(
          Map.entry("ReturnLeft", ReturnLeft),
          Map.entry("ReturnRight", ReturnRight),
          Map.entry("RushLeft", RushLeft),
          Map.entry("RushRight", RushRight));

  /**
   * Looks up the ChoreoTraj segment of the given overall ChoreoTraj. WARNING: will raise an
   * exception if not called with a valid segment index.
   */
  public ChoreoTraj segment(int segment) {
    var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
    if (traj == null) {
      throw new NullPointerException(
          "Trajectory " + this.name + " does not have segment #" + segment + ".");
    }
    return traj;
  }
}
