package frc.robot.constants.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories, and removes the need
 * for JSON parsing to load a trajectory's essential data. DO NOT MODIFY THIS FILE YOURSELF! It is
 * automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue) {
  public static final ChoreoTraj Test =
      new ChoreoTraj(
          "Test",
          OptionalInt.empty(),
          6.99646,
          new Pose2d(2.004, 5.268, Rotation2d.fromRadians(0.785)),
          new Pose2d(2.142, 2.608, Rotation2d.fromRadians(2.172)));

  /**
   * A map between trajectory names and their corresponding data. This allows for trajectory data to
   * be looked up with strings during runtime.
   */
  public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES =
      Map.ofEntries(Map.entry("Test", Test));

  /**
   * Looks up the ChoreoTraj segment of the given overall ChoreoTraj. WARNING: will raise an
   * exception if not called with a valid segment index.
   */
  public ChoreoTraj segment(int segment) {
    var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
    if (traj == null) {
      throw new NullPointerException(
          "Trajectory " + this.name + " does not have segment #" + segment + ".");
    }
    return traj;
  }
}
