package frc.robot.constants.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories, and removes the need
 * for JSON parsing to load a trajectory's essential data. DO NOT MODIFY THIS FILE YOURSELF! It is
 * automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue) {
  public static final ChoreoTraj FirstCenterCollect =
      new ChoreoTraj(
          "FirstCenterCollect",
          OptionalInt.empty(),
          5.62417,
          new Pose2d(4, 7.43, Rotation2d.fromRadians(0)),
          new Pose2d(2.38, 6.75, Rotation2d.fromRadians(-0.88)));
  public static final ChoreoTraj FirstCenterCollect$0 =
      new ChoreoTraj(
          "FirstCenterCollect",
          OptionalInt.of(0),
          3.22776,
          new Pose2d(4, 7.43, Rotation2d.fromRadians(0)),
          new Pose2d(7.819, 4.938, Rotation2d.fromRadians(-1.7)));
  public static final ChoreoTraj FirstCenterCollect$1 =
      new ChoreoTraj(
          "FirstCenterCollect",
          OptionalInt.of(1),
          2.3964100000000004,
          new Pose2d(7.819, 4.938, Rotation2d.fromRadians(-1.7)),
          new Pose2d(2.38, 6.75, Rotation2d.fromRadians(-0.88)));
  public static final ChoreoTraj SecondCenterCollect =
      new ChoreoTraj(
          "SecondCenterCollect",
          OptionalInt.empty(),
          6.63169,
          new Pose2d(2.38, 6.75, Rotation2d.fromRadians(-0.88)),
          new Pose2d(2.38, 6.75, Rotation2d.fromRadians(-0.88)));
  public static final ChoreoTraj SecondCenterCollect$0 =
      new ChoreoTraj(
          "SecondCenterCollect",
          OptionalInt.of(0),
          4.74101,
          new Pose2d(2.38, 6.75, Rotation2d.fromRadians(-0.88)),
          new Pose2d(7.696, 6.042, Rotation2d.fromRadians(1.571)));
  public static final ChoreoTraj SecondCenterCollect$1 =
      new ChoreoTraj(
          "SecondCenterCollect",
          OptionalInt.of(1),
          1.8906799999999997,
          new Pose2d(7.696, 6.042, Rotation2d.fromRadians(1.571)),
          new Pose2d(2.38, 6.75, Rotation2d.fromRadians(-0.88)));

  /**
   * A map between trajectory names and their corresponding data. This allows for trajectory data to
   * be looked up with strings during runtime.
   */
  public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES =
      Map.ofEntries(
          Map.entry("FirstCenterCollect", FirstCenterCollect),
          Map.entry("FirstCenterCollect$0", FirstCenterCollect$0),
          Map.entry("FirstCenterCollect$1", FirstCenterCollect$1),
          Map.entry("SecondCenterCollect", SecondCenterCollect),
          Map.entry("SecondCenterCollect$0", SecondCenterCollect$0),
          Map.entry("SecondCenterCollect$1", SecondCenterCollect$1));

  /**
   * Looks up the ChoreoTraj segment of the given overall ChoreoTraj. WARNING: will raise an
   * exception if not called with a valid segment index.
   */
  public ChoreoTraj segment(int segment) {
    var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
    if (traj == null) {
      throw new NullPointerException(
          "Trajectory " + this.name + " does not have segment #" + segment + ".");
    }
    return traj;
  }
}
